
[Settings]
ID = "89939d91-1a21-4480-a140-9336ac81b013" 


# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "React-Todo"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "React-Todo/build/"
  # This will be your default build command
  command = "yarn build"